### PR TITLE
Fix `ite` in model generation

### LINKED ISSUE #275: ASSERTION VIOLATION when requesting model
I found that the following very small example triggers an internal assertion failure in Z3-Noodler when requesting a model:

```smt
(set-logic ALL)
(declare-fun f0 (String String) Bool)
(declare-const c0 String)
(declare-const c1 String)
(define-const v1 Int  (str.len (str.replace_all c1 "/" "-")))
(define-const v2 String (ite (= v1 0) "" "1"))
(assert (f0 c0 v2))
(check-sat)
```

Running Z3-Noodler without model construction returns `sat`, which is expected.
If I ask for a model, CVC5 is able to produce a reasonable one, e.g.:

```smt
(
(define-fun f0 ((_arg_1 String) (_arg_2 String)) Bool true)
(define-fun c0 () String "")
(define-fun c1 () String "")
)
```

However, Z3-Noodler crashes when model construction is requested:

```
ASSERTION VIOLATION
File: z3-noodler/src/smt/theory_str_noodler/theory_str_noodler_model.cpp
Line: 181
UNEXPECTED CODE WAS REACHED.
4.15.1.0 d5caee9f4e3ab3816871721bc189333792b1aa03
Please file an issue with this message and more detail about how you encountered it at https://github.com/Z3Prover/z3/issues/new
```

This assertion failure appears during the model-building phase, even though the instance itself is satisfiable.
The example above is already the minimal formula needed to trigger the crash.

For reference:
Z3 returns `unknown` on this input, as expected, since str.replace_all is not fully supported.

### PR DESCRIPTION
**Pull request by jurajsic**
Fixes #275

### CODE REVIEW

File: src/smt/theory_str_noodler/theory_str_noodler.h [hunk 1]
```diff
@@ -409,6 +409,9 @@ namespace smt::noodler {
         /// @brief Returns the model_value_proc for string variable @p str_expr based on whether it is used in dec_proc or not
         model_value_proc* model_of_string_var(app* str_var);
 
+        /// @brief Handles (revursively) ITE in @p e in model generation
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/theory_str_noodler.h]: recursively

**Review by vhavlena — APPROVED** [review]
Nice!

File: src/smt/theory_str_noodler/theory_str_noodler.h (hunk 1 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler.h]:
```suggestion
        /// @brief Handles (recursively) ITE in @p e in model generation
```
