### PR TITLE
Fix var clashing var names

### LINKED ISSUE #274: Clashing of internal string variables with user-declared ones
For
```
(declare-fun to_int_result!n0 () String)
(assert (> (str.to_int to_int_result!n0) (str.len to_int_result!n0)))
(assert (str.in_re to_int_result!n0 (re.++ (str.to_re "0") (re.range "2" "2"))))
```
we return `sat` instead of `unsat`.

The problem is that `to_int_result!n0` is the internal name of the variable for the result of `(str.to_int to_int_result!n0)`, which is saved to the mapping `var_name` (we map out internal `to_int_result!n0` var to `(str.to_int to_int_result!n0)`) . However, this is later mapped to the string var `to_int_result!n0`. So when we create len formula, we put always `(str.len to_int_result!n0)`, but we need to differentiate `(str.to_int to_int_result!n0)`.

I will fix it after merging #268

### PR DESCRIPTION
**Pull request by jurajsic**
Fixes #274 by prepending the character @ at the beginning of our internal variables (according to SMT-LIB, symbols starting with the character @ or . are reserved for solver use).

I also updated the mapping of noodler variables to Z3 vars (`var_name`). It is done in `relevant_eh()`, instead of in various places in final_check. This means that I also removed multiple unused functions.

### CODE REVIEW

**Comment by jurajsic** [comment]
Results:
```
# of formulae: 106648
--------------------------------------------------
tool                                  ✅    ❌        time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  ----  ----------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-1e6a937-1fc91ef        105824   824    10831.26   0.10   0.00   1.45  64042    41782        537   232        55        0
z3-noodler-6153947-1fc91ef        105815   833    11218.03   0.11   0.00   1.51  64032    41783        537   236        60        0
z3-noodler-model-1e6a937-1fc91ef  105810   838    11836.51   0.11   0.01   1.50  64028    41782        550   229         0       59
z3-noodler-model-6153947-1fc91ef  105801   847    12123.62   0.11   0.01   1.57  64018    41783        549   231         0       67
--------------------------------------------------
```
image

File: src/smt/theory_str_noodler/regex.cpp [hunk 1]
```diff
@@ -1026,15 +1026,15 @@ namespace smt::noodler::regex {
         return result;
     }
 
-    void gather_transducer_constraints(app* ex, ast_manager& m, const seq_util& m_util_s, obj_map<expr, expr*>& pred_replace, std::map<BasicTerm, expr_ref>& var_name, const regex::Alphabet& alph, Formula& transducer_preds) {
+    void gather_transducer_constraints(app* ex, ast_manager& m, const seq_util& m_util_s, obj_map<expr, expr*>& pred_replace, const regex::Alphabet& alph, Formula& transducer_preds) {
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/regex.cpp:1029]: `var_name` is not needed anymore?

**Review by vhavlena — APPROVED** [review]
Nice! Can you add the problematic formula from the issue among the end-to-end tests?

File: src/smt/theory_str_noodler/regex.cpp (hunk 1 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/regex.cpp:1029]: Nope, the only reason it was there is because there was a call to `collect_terms`, from which I removed it too (as the mapping is done on `relevant_eh()` level)

Comment (vhavlena) [reply src/smt/theory_str_noodler/regex.cpp:1029]: Ok, that's nice.

**Comment by vhavlena** [comment]
The results are nice. Do you have an idea what was the cause?

**Comment by jurajsic** [comment]
> The results are nice. Do you have an idea what was the cause?

Don't know, probably because all variables have different names so Z3 is doing different choices.
