### PR TITLE
Fix literals in transducers

### LINKED ISSUE #301: `std::out_of_range` crash when running with model generation
While #292 resolved the crash without model generation, I found this mirror case.
Using the original example below:

```smt
(set-logic QF_SLIA)
(declare-fun v0 () String)
(declare-fun v1 () String)
(assert (= (str.++ v0 "eee") (str.++ "fe" v1)))
(assert (> (str.len (str.replace_all v1 "e" ".")) 1))
(assert (= "" (str.substr (str.replace_all v0 "e" ".") 0 (str.indexof (str.replace_all v0 "e" ".") "." 0))))
(check-sat)
(get-model)
```

Currently, cvc5 correctly return `sat` and generate the model like this:

```smt
sat
(
(define-fun v0 () String "f")
(define-fun v1 () String "ee")
)
```

And z3-noodler without `model=true` returns `sat`. That's right.
However, if I use `model=true`, z3-noodler crashes with the following error:

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

For reference, I am using the latest version of z3-noodler: 

```
Z3 version 4.15.1 - 64 bit 
- build hashcode 3630fde353e9f86421f43de36e58ab6ca5443d0e
- mata hashcode 93d7964f0af93df234d9958e8fe3a5f70c9f0651
```

### PR DESCRIPTION
**Pull request by jurajsic**
Fixes check for literals in the function pushing non-simple transducers (we need to have non-literals on output of transducer constraints that have lengths in input).

### CODE REVIEW

**Comment by jurajsic** [comment]
Results on transducer benchmarks:
```
# of formulae: 2431
--------------------------------------------------
tool                                ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ec26a16-1fc91ef        1878   553    464.55   0.25   0.01   3.17    657     1221        501    49         3        0
z3-noodler-3630fde-1fc91ef        1878   553    475.94   0.25   0.01   3.24    657     1221        501    49         3        0
z3-noodler-model-ec26a16-1fc91ef  1880   551    633.48   0.34   0.01   4.66    659     1221        500    49         2        0
z3-noodler-model-3630fde-1fc91ef  1880   551    549.37   0.29   0.01   3.86    659     1221        500    49         2        0
--------------------------------------------------


Benchmark webapp
# of formulae: 340
--------------------------------------------------
tool                                ✅    ❌     time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  -------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ec26a16-1fc91ef         338     2    18.10   0.05   0.00   0.35    121      217          1     1         0        0
z3-noodler-3630fde-1fc91ef         338     2    18.12   0.05   0.00   0.35    121      217          1     1         0        0
z3-noodler-model-ec26a16-1fc91ef   340     0   115.31   0.34   0.01   5.14    123      217          0     0         0        0
z3-noodler-model-3630fde-1fc91ef   340     0   114.65   0.34   0.01   5.12    123      217          0     0         0        0
--------------------------------------------------

Benchmark transducer_plus
# of formulae: 91
--------------------------------------------------
tool                                ✅    ❌    time    avg    med     std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  ------  -----  -----  ------  -----  -------  ---------  ----  --------  -------
z3-noodler-ec26a16-1fc91ef          40    51  438.79  10.97   0.29   18.99     36        4          0    48         3        0
z3-noodler-3630fde-1fc91ef          40    51  449.91  11.25   0.31   19.42     36        4          0    48         3        0
z3-noodler-model-ec26a16-1fc91ef    40    51  507.53  12.69   0.41   25.58     36        4          0    49         2        0
z3-noodler-model-3630fde-1fc91ef    40    51  424.34  10.61   0.38   19.42     36        4          0    49         2        0
--------------------------------------------------

Benchmark pcp
# of formulae: 1000
--------------------------------------------------
tool                                ✅    ❌      time     avg     med     std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  --------  ------  ------  ------  -----  -------  ---------  ----  --------  -------
z3-noodler-ec26a16-1fc91ef         500   500      0.17    0.00    0.00    0.00      0      500        500     0         0        0
z3-noodler-3630fde-1fc91ef         500   500      0.21    0.00    0.00    0.00      0      500        500     0         0        0
z3-noodler-model-ec26a16-1fc91ef   500   500      0.74    0.00    0.00    0.00      0      500        500     0         0        0
z3-noodler-model-3630fde-1fc91ef   500   500      0.82    0.00    0.00    0.00      0      500        500     0         0        0
--------------------------------------------------

Benchmark rna
# of formulae: 1000
--------------------------------------------------
tool                                ✅    ❌     time     avg     med     std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  -------  ------  ------  ------  -----  -------  ---------  ----  --------  -------
z3-noodler-ec26a16-1fc91ef        1000     0     7.49    0.01    0.01    0.00    500      500          0     0         0        0
z3-noodler-3630fde-1fc91ef        1000     0     7.70    0.01    0.01    0.00    500      500          0     0         0        0
z3-noodler-model-ec26a16-1fc91ef  1000     0     9.90    0.01    0.01    0.00    500      500          0     0         0        0
z3-noodler-model-3630fde-1fc91ef  1000     0     9.56    0.01    0.01    0.00    500      500          0     0         0        0
--------------------------------------------------
```
image

File: src/smt/theory_str_noodler/solving_state.h [hunk 1]
```diff
@@ -118,14 +118,14 @@ namespace smt::noodler {
...
-         * @brief Adds all transducers that contain length vars on input and are not simple (they do not have one input and one output var) back to processing.
+         * @brief Adds all transducers that contain length vars on input and are not simple (they do not have one input and one output var, or output is literal) back to processing.
          * 
          * It pushes a transducer only if it is not pushed already.
          * Useful after calling substitute_vars().
          */
         void push_non_simple_transducers_to_processing() {
             for (const Predicate &transducer : transducers) {
-                if (contains_length_var(transducer.get_input()) && (transducer.get_input().size() != 1 || transducer.get_output().size() != 1 || transducer.get_input()[0].is_literal() || transducer.get_input()[1].is_literal())) {
+                if (contains_length_var(transducer.get_input()) && (transducer.get_input().size() != 1 || transducer.get_output().size() != 1 || transducer.get_output()[0].is_literal())) {
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/solving_state.h:128]: Literals on input are not interesting anymore?

File: src/smt/theory_str_noodler/decision_procedure.cpp [hunk 2]
```diff
@@ -427,7 +427,7 @@ namespace smt::noodler {
                                                             noodle[i].input_aut, // we assign Ai to new_input_var
                                                             std::string("input_") + std::to_string(noodlification_no),
                                                             new_element.contains_length_var(input_vars_divisions[noodle[i].input_index]),
-                                                            false // we do not want literals in simple transducers
+                                                            true
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/decision_procedure.cpp:430]: So, now it might happen that singleton variable becomes literal (in `add_fresh_var`), which may lead to additional splitting (in `push_non_simple_transducers_to_processing`)?

**Review by vhavlena — APPROVED** [review]
Nice work!

File: src/smt/theory_str_noodler/solving_state.h (hunk 1 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/solving_state.h:128]: They were never interesting, but when I wrote this condition I did not know exactly what I was fixing. The problem is that for models, we need to have that if input var is length, then the output var is also length (which does not hold for literals). And during the procedure, it can happen that a simple transducer `x = T(y)` will change to `"some literal" = T(y)` because `x` will be substituted, so we need to process it again.

File: src/smt/theory_str_noodler/decision_procedure.cpp (hunk 2 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/decision_procedure.cpp:430]: There shouldn't be splitting coming from this, because if we had a simple transducer `x = T(y)` where x becomes a literal `l`, we will make an inclusion `x' = y` where `L(x') = T^-1(l)`. So it can lead to further refining, but no splitting. And it will remove the transducer from length generation, so it might be helpful.
