### PR TITLE
Fix: Simple quantifiers

### LINKED ISSUE #276: Parser error and crash in Z3-Noodler when quantified formulas involve strings
I encountered a parser-related issue in Z3-Noodler when a quantified formula involves strings.
The formula is the following:

```smt
(set-logic ALL)
(declare-fun fun0 (String String Int) String)
(define-const c0 String ".")
(declare-const v0 String)
(assert (forall ((i Int))
    (>= (str.len (fun0 v0 "." i)) 1)))
(check-sat)
(get-model)
```

Z3 accepts this input, returns `sat`, and can produce a model such as:

```smt
(
  (define-fun v0 () String ".")
  (define-fun c0 () String ".")
  (define-fun fun0 ((x!0 String) (x!1 String) (x!2 Int)) String "!0!")
)
```

Z3-Noodler instead reports a parser error:

```
ERROR: unexpected character: '2 2'.
WARNING: parser error
WARNING: invalid cost function '', switching to default one
unknown
```

I understand that quantified formulas over the string theory are generally outside the intended scope of Z3-Noodler, but I believe this input should not trigger a parsing failure.
In addition, If I remove the unused constant declaration:

```smt
(define-const c0 String ".")
```

Z3-Noodler crashes with a different error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```
It is unclear whether the two errors share the same underlying cause, but both behaviors seem unexpected given that the input is syntactically valid SMT-LIB.

### PR DESCRIPTION
**Pull request by vhavlena**
This pull request introduces a significant refactoring and extension of the internal LIA (Linear Integer Arithmetic) solver infrastructure in the Noodler string theory solver, as well as improvements to quantifier handling and model generation. The changes add a new abstract interface for LIA solvers, unify the interface for quantifier-free and quantified LIA solvers, improve unsat core extraction, and enhance model value generation for string variables.

### CODE REVIEW

**Comment by vhavlena** [comment]
Results:
```
# of formulae: 106648
--------------------------------------------------
tool                                  ✅    ❌        time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  ----  ----------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ff2475a-1fc91ef        105818   830    11004.45   0.10   0.00   1.47  64035    41783        537   233        60        0
z3-noodler-6153947-1fc91ef        105815   833    11218.03   0.11   0.00   1.51  64032    41783        537   236        60        0
cvc5-1.3.1                        100246  6402    70919.81   0.71   0.00   6.22  61078    39168        132  6262         0        8
z3-4.15.4                          96858  9790    95319.17   0.98   0.00   6.71  57869    38989       2227  5815      1748        0
ostrich-2-fmcad25                 103115  3533  1034421.06  10.03   2.01  20.76  62273    40842          3  3529         0        1
z3-noodler-model-ff2475a-1fc91ef  105804   844    11860.14   0.11   0.01   1.51  64021    41783        549   229         0       66
z3-noodler-model-6153947-1fc91ef  105801   847    12123.62   0.11   0.01   1.57  64018    41783        549   231         0       67
check-model-ff2475a-1fc91ef       104639  2009    13693.98   0.13   0.00   3.26  62856    41783        549   632         0      828
--------------------------------------------------
```

image

(nothing interesting)

**Comment by vhavlena** [comment]
The handling of quantifiers is still very limited, but at least it could help for quantified formulae that do not interact much with the string part. It should at least fix #276

File: src/smt/theory_str_noodler/lia_solver.h [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+        /**
+         * @brief Virtual destructor.
+         */
+        virtual ~lia_solver() = default;
+
+        /**
+         * @brief Initialize the solver with formulas present in the given Z3 `context`.
+         *
+         * @param ctx The Z3 `context` from which to take asserted formulas and current assignment.
+         * @param include_ass If true, include current assignment formulas as part of initialization.
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/lia_solver.h]: Could you explain what "assignment formulas" are here? Or maybe just some hint to some other piece of code/comment. I always forget what this parameter does and this doesn't explain it properly.
Also change the name to `include_assignment` :D

File: src/smt/theory_str_noodler/quant_lia_solver.h [hunk 2]
```diff
@@ -42,11 +45,12 @@ namespace smt::noodler {
 
             // another options for a solver: mk_smt_solver(m, p, symbol("LIA")); (no tactic)
             // tactic solver used by z3 to solve quantified LIA formula
-            solver* sl = mk_tactic2solver(m, mk_lia_tactic(m, p), p, false, true, false, symbol("ALL"));
+            solver* sl = mk_tactic2solver(m, mk_lia_tactic(m, p), p, false, true, true, symbol("ALL"));
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/quant_lia_solver.h:48]: What is the argument that changed from `false` to `true`?

File: src/smt/theory_str_noodler/quant_lia_solver.h [hunk 3]
```diff
@@ -42,11 +45,12 @@ namespace smt::noodler {
...
 
             erv.push_back(e);
             sl->assert_expr(erv);
             auto res = sl->check_sat();
+            sl->get_unsat_core(unsat_core);
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/quant_lia_solver.h:53]: Is it possible this will make it slower?

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 4]
```diff
@@ -157,77 +158,76 @@ namespace smt::noodler {
 
     }
 
-    void theory_str_noodler::string_theory_propagation(expr *expr, bool init, bool neg, bool var_lengths) {
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler.cpp:160]: Why did you change the name? I agree that the change is good, I just want to know if there was some problem?

File: src/smt/theory_str_noodler/quant_lia_solver.h (hunk 2 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/quant_lia_solver.h:48]: Now it should generate unsat cores (hopefully).

File: src/smt/theory_str_noodler/quant_lia_solver.h (hunk 3 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/quant_lia_solver.h:53]: Yes, I think so. Fortunately, this solver is used only when quantified formulae occur, which is not that often (from our benchmarks just the position_hard). But if we want to properly support quantifiers, it is necessary I think.

File: src/smt/theory_str_noodler/theory_str_noodler.cpp (hunk 4 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp:160]: I made a quite a lot of attempts to handle the quantifiers. One of them was modifying the `string_theory_propagation` (do something special for quantifiers). For that I needed to declare sth like `obj_hastable<expr>` and the type was clashing with the variable name. I eventually removed the code as it was not working but I kept the renaming there as it might be useful.

File: src/smt/theory_str_noodler/lia_solver.h (hunk 1 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/lia_solver.h]: Sure, let's make the code joke-free 😄 I also updated the comment.

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp [hunk 5]
```diff
@@ -1134,7 +1146,12 @@ namespace smt::noodler {
             // WARNING: the model generation is not supported for tag automata stuff. 
             // In order to add a support of model generation we need to handle adding axioms in the form of quantified formulae 
             // (so-far the internal solver timeouts with quntified axioms)
-            add_axiom(length_formula);
+            if(this->input_has_quantifiers) {
+                ctx.assert_expr(sat_length_formula);
+                ctx.internalize_assertions();
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1155]: What is this for? I would add some comment.

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp [hunk 6]
```diff
@@ -74,16 +79,34 @@ namespace smt::noodler {
     
         app * mk_value(model_generator & m, expr_ref_vector const & values) override {
             if (!length_relevant) {
-                // because the length is not relevant, we can return anything, so we return empty string
+                // because the length is not relevant, we can return any string; let the
+                // standard sequence factory pick a fresh value when available, to avoid
+                // collapsing the string universe to a single element.
+                // try to obtain the seq_factory from the proto_model owned by
+                // the model generator and use it to pick a fresh string value
+                // when available.
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_model.cpp:87]: This seems like something I was trying to do in #282.

Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler_model.cpp:87]: The "fresh" value will not be completely fresh, it might be the same as some string returned by us in the decision procedure, right?

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp [hunk 7]
```diff
@@ -74,16 +79,34 @@ namespace smt::noodler {
...
-                return m_util_s.str.mk_string(zstring(res.size(), res.data()));
+                unsigned len = val.get_unsigned();
+                std::vector<unsigned> res(len, 'a');
+                expr* v = m_util_s.str.mk_string(zstring(res.size(), res.data()));
+                proto_model& mdl = m.get_model();
+                value_factory* vf = mdl.get_factory(m_util_s.get_family_id());
+                if (auto* f = dynamic_cast<seq_factory*>(vf)) {
+                    f->register_value(v);
+                }
+                return to_app(v);
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_model.cpp:126]: Shouldn't we return a fresh value also here? If we get some length variable both with lengths 2, they will have "aa" as model.

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp (hunk 6 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler_model.cpp:87]: Also, what was the problem with the collapse? I assume something with quantifiers.

File: src/smt/theory_str_noodler/util.cc [hunk 8]
```diff
@@ -596,4 +596,32 @@ namespace smt::noodler::util {
...
+        struct has_bound_var_proc {
+            bool found = false;
+            void operator()(expr* e) {
+                if (is_var(e)) // bound variable (quantified)
+                    found = true;
+            }
+        };
+
+        has_bound_var_proc proc;
+        for_each_expr(proc, e);
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/util.cc:612]: Cool find, what does the `for_each_expr` do?

File: src/smt/theory_str_noodler/util.cc [hunk 9]
```diff
@@ -596,4 +596,32 @@ namespace smt::noodler::util {
 
         return std::nullopt;
     }
-}
+
+    bool has_quanfied_vars(ast_manager& m, expr* e) {
+        struct has_bound_var_proc {
+            bool found = false;
+            void operator()(expr* e) {
+                if (is_var(e)) // bound variable (quantified)
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/util.cc:606]: Does this mean that if there is any var, it is assumed it is bounded?

File: src/smt/theory_str_noodler/util.cc [hunk 10]
```diff
@@ -596,4 +596,32 @@ namespace smt::noodler::util {
...
+                if (is_quantifier(e))
+                    found = true;
+            }
+        };
+
+        has_quantifier_proc proc;
+        for_each_expr(proc, e);
+        return proc.found;
+    }
+}
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/util.cc]:
```suggestion
}

```

File: src/test/noodler/e2e/quantif-int.smt2 [hunk 11]
```diff
@@ -0,0 +1,9 @@
+(set-logic ALL)
+(set-info :status sat)
+(declare-fun fun0 (String String Int) String)
+(define-const c0 String ".")
+(declare-const v0 String)
+(assert (forall ((i Int))
+    (>= (str.len (fun0 v0 "." i)) 1)))
+(check-sat)
+(get-model)
```
Comment (jurajsic) [inline src/test/noodler/e2e/quantif-int.smt2]:
```suggestion
(get-model)

```

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp [hunk 12]
```diff
@@ -208,9 +237,15 @@ namespace smt::noodler {
...
+            mg.register_factory(m_seq_factory);
+        }
     }
 
     void theory_str_noodler::finalize_model(model_generator &mg) {
         STRACE(str, tout << "finalize_model\n";);
+        // factory lifetime is managed by the model; just clear our pointer
+        m_seq_factory = nullptr;
     }
 }
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_model.cpp]:
```suggestion
}

```

File: src/smt/theory_str_noodler/quant_lia_solver.h (hunk 3 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/quant_lia_solver.h:53]: Why is it necessary?

Maybe we could at least move it to `get_unsat_core()`, add some bool member that will remember whether we need to `pop_back()` and if another `assert()` or `check_sat()` is called, we first pop back.

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp (hunk 6 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_model.cpp:87]: The fresh might not be unique across the whole assignment I think. The problem with collapsing appears for the models of quantified formulae (the model was some ugly quantified formula).

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp (hunk 7 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_model.cpp:126]: I think it is not a problem?

File: src/smt/theory_str_noodler/util.cc (hunk 8 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/util.cc:612]: That's a expr ast crawler. You define a type with operator() and the operator is called on every node.

File: src/smt/theory_str_noodler/theory_str_noodler_model.cpp (hunk 7 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler_model.cpp:126]: I do not know, it depends on why we need fresh value for the non-length case :D

File: src/smt/theory_str_noodler/util.cc (hunk 9 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/util.cc:606]: Yes. AFAIK free variables are nulary applications. For the bounded variables De Bruijn indices are used (so they are basically numbers).

Comment (jurajsic) [reply src/smt/theory_str_noodler/util.cc:606]: Ah, it is not our function for testing whether something is a variable, but it is testing for the theory var, or something like that, right?

> Yes. AFAIK free variables are nulary applications. For the bounded variables De Bruijn indices are used (so they are basically numbers).

Can you add this as a comment in code?

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp (hunk 5 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1155]: I added a comment.

File: src/smt/theory_str_noodler/util.cc (hunk 9 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/util.cc:606]: I added a comment.

File: src/smt/theory_str_noodler/quant_lia_solver.h (hunk 3 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/quant_lia_solver.h:53]: It could be definitely made more efficient. In that case you need to create the solver as a class member and handle everything more properly (and there were some unexpected strange issues if I remember correctly). It is a similar reason, why I needed to create solvers in `check_len_sat` as local variables (when I used the classical pattern of using unique pointer with a base class and then dynamically decide which class you use, I was still getting `unknown` from the solver; don't know why). Moreover, we do not aim at quantified formulae (for most of them we will be giving unknown), so I would keep it for further optimizations (if you don't insist of course).

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp (hunk 5 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1155]: You added the comment to `final_check_eh` but you should also add it here (`sat_handling()`).

Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1155]: good catch
