### PR TITLE
Handle `replace_re` using transducers

### LINKED ISSUE #346: Incorrect match for `replace_re`
For
```
(set-logic QF_SLIA)
(declare-fun x () String)
(declare-fun y () String)
(assert (= x (str.replace_re y (re.++ (str.to_re "a") re.all (str.to_re "b")) "c")))
(assert (str.in_re y (re.++ (str.to_re "aab") re.allchar)))
(assert (<= 3 (str.len x)))
(check-sat)
```
we return `sat` even though it is `unsat`.
The formula takes `y = aab.` and should replace leftmost shortest match of `a.*b` in `y` with `c`. That is `aab`, not `ab`, i.e. |x|=2. But we can match both. It is probably problem with the axiomatization of `replace_re`.

### PR DESCRIPTION
**Pull request by jurajsic**
Should fix #346

### CODE REVIEW

**Comment by jurajsic** [comment]
```
# of formulae: 133722
--------------------------------------------------
tool                                  ✅     ❌        time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  -----  ----------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ef03b57-1c39000        131598   2124    12041.10   0.09   0.00   1.52  84653    46945        782  1210       128        4
z3-noodler-ab0c64e-1c39000        131622   2100    12417.40   0.09   0.00   1.55  84677    46945        756  1214       126        4
z3-noodler-model-ef03b57-1c39000  131591   2131    13464.58   0.10   0.01   1.60  84646    46945        779  1216       132        4
z3-noodler-model-ab0c64e-1c39000  131614   2108    13637.72   0.10   0.01   1.59  84669    46945        752  1221       131        4
--------------------------------------------------

Benchmark webapp
# of formulae: 681
--------------------------------------------------
tool                                ✅    ❌     time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  -------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ef03b57-1c39000         678     3    26.97   0.04   0.01   0.26    249      429          1     2         0        0
z3-noodler-ab0c64e-1c39000         679     2    73.96   0.11   0.01   1.73    250      429          1     1         0        0
z3-noodler-model-ef03b57-1c39000   681     0   135.47   0.20   0.01   2.82    252      429          0     0         0        0
z3-noodler-model-ab0c64e-1c39000   681     0   133.04   0.20   0.01   2.77    252      429          0     0         0        0
--------------------------------------------------

Benchmark strict_bj
# of formulae: 25206
--------------------------------------------------
tool                                 ✅     ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  -----  -----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-ef03b57-1c39000        24235    971   2775.12   0.11   0.00   2.41  20353     3882        245   683        41        2
z3-noodler-ab0c64e-1c39000        24258    948   2832.56   0.12   0.00   2.45  20376     3882        219   686        41        2
z3-noodler-model-ef03b57-1c39000  24238    968   3177.43   0.13   0.01   2.50  20356     3882        229   693        44        2
z3-noodler-model-ab0c64e-1c39000  24261    945   3143.19   0.13   0.01   2.44  20379     3882        202   697        44        2
--------------------------------------------------
```
image

File: src/smt/theory_str_noodler/regex.cpp [hunk 1]
```diff
@@ -1087,15 +1087,20 @@ namespace smt::noodler::regex {
         // collect all nested replace_all and replace_re_all and keep their arguments as pairs
         // in find_and_replace (where find can be either zstring for replace_all or NFA for 
         // replace_re_all)
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/regex.cpp]:
```suggestion
        // collect all nested replace_all/replace_re/replace_re_all and keep their arguments as pairs
        // in find_and_replace (where find can be either zstring for replace_all or NFA for 
        // replace_re/replace_re_all)
```

**Review by vhavlena — APPROVED** [review]
Nice!
