### PR TITLE
Fix literal propagation in Length procedure

### LINKED ISSUE #366: Length procedure giving incorrect results
The formula
```smt2
(set-logic QF_SLIA)

(declare-const x String)
(declare-const a String)
(declare-const b String)
(declare-const i Int)
(declare-const j Int)
(assert (str.in_re a (re.* (str.to_re "a"))))
(assert (str.in_re b (re.* (str.to_re "b"))))
(assert (= (str.len a) 4))
(assert (= (str.len b) 4))
(assert (= x (str.++ a b)))
(assert (= (str.substr x i j) "abba"))

(check-sat)
(get-model)
```
should be `unsat`, but noodler returns
```
sat
(
  (define-fun x () String
    "aaaabbaa")
  (define-fun a () String
    "aaaa")
  (define-fun j () Int
    4)
  (define-fun b () String
    "bbaa")
  (define-fun i () Int
    3)
)
```

The problem is probably somewhere in the length decision procedure, because it correctly gives `unsat` if you turn it off using `smt.str.try_length_proc=false`

### PR DESCRIPTION
**Pull request by vhavlena**
This pull request fixes handling of literals in length-based decision procedure.

### CODE REVIEW

**Comment by vhavlena** [comment]
Basically no impact:
```
# of formulae: 133722
--------------------------------------------------
tool                                  ✅     ❌       time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  -----  ---------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-a7872ed-1c39000        132129   1593   14859.36   0.11   0.00   1.82  85151    46978        656   817       116        4
z3-noodler-c2ac728-1c39000        132128   1594   14767.01   0.11   0.00   1.79  85150    46978        656   818       116        4
z3-noodler-model-a7872ed-1c39000  132153   1569   15515.78   0.12   0.01   1.77  85176    46977        619   825       121        4
z3-noodler-model-c2ac728-1c39000  132154   1568   15700.50   0.12   0.01   1.81  85177    46977        619   823       122        4
--------------------------------------------------
```

image

File: src/smt/theory_str_noodler/formula_preprocess.cpp [hunk 1]
```diff
@@ -375,6 +375,39 @@ namespace smt::noodler {
...
+                singletons.push_back({v, found_literal});
+            }
+        }
+        for (const auto& [v, word_str] : singletons) {
+            BasicTerm lit(BasicTermType::Literal, word_str);
+            this->aut_ass[lit] = this->aut_ass.at(v);
+            this->formula.replace({v}, {lit});
+            substitute_var(v, {lit});
+        }
+    }
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/formula_preprocess.cpp:410]:
```suggestion
        STRACE(str_prep, tout << print_info(is_trace_enabled(TraceTag::str_nfa)));
    }
```

File: src/test/noodler/e2e/issue366.smt2 [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+(declare-const i Int)
+(declare-const j Int)
+(assert (str.in_re a (re.* (str.to_re "a"))))
+(assert (str.in_re b (re.* (str.to_re "b"))))
+(assert (= (str.len a) 4))
+(assert (= (str.len b) 4))
+(assert (= x (str.++ a b)))
+(assert (= (str.substr x i j) "abba"))
+
+(check-sat)
```
Comment (jurajsic) [inline src/test/noodler/e2e/issue366.smt2]:
```suggestion
(check-sat)

```

File: .gitignore [hunk 3]
```diff
@@ -118,3 +118,4 @@ genaisrc/genblogpost.genai.mts
 bazel-*
 # Local issue tracking
 .beads
+.claude
```
Comment (jurajsic) [inline .gitignore]:
```suggestion
.claude

```

**Review by jurajsic — APPROVED** [review]

**Comment by jurajsic** [comment]
What was the problem?

**Comment by vhavlena** [comment]
> What was the problem?

Some variables having singleton language failed to be marked as literals and hence the languages of these variables were ignored in length-based procedure (length-based procedure distinguish only unbounded variables or literals).

File: src/smt/theory_str_noodler/formula_preprocess.cpp [hunk 4]
```diff
@@ -375,6 +375,40 @@ namespace smt::noodler {
...
+        for (const BasicTerm& v : all_vars) {
+            if (!this->aut_ass.count(v)) continue;
+            mata::nfa::Nfa aut = *this->aut_ass.at(v);
+            aut.trim();
+            zstring found_literal;
+            // aut_encodes_literal rejects automata with dummy-symbol transitions,
+            // preventing false positives for variables constrained to re.allchar
+            // over a collapsed (dummy) alphabet.
+            if (AutAssignment::aut_encodes_literal(aut, found_literal)) {
+                singletons.push_back({v, found_literal});
```
[the remark this answers is not in the document]
Comment (vhavlena) [reply src/smt/theory_str_noodler/formula_preprocess.cpp:400]: Added a reduction.
