### PR TITLE
Handle functions refactoring

### LINKED ISSUE #333: Incorrect result for `str.substr`
For
```
(set-logic QF_SLIA)
(set-info :status sat)
(declare-const x String)
(declare-const y String)
(declare-const u String)
(assert (= y (str.substr x 0 (+ 1 (str.indexof x "cd" 1)))))
(assert (str.in_re x (re.++ (re.range "d" "z") re.allchar (str.to_re "cd"))))
(assert (< 1 (str.len y)))
(assert (= u (str.++ (str.substr x 0 (str.indexof x "cd" 1)) "cd")))
(assert (distinct u y))
(check-sat)
```
we return `unsat` instead of `sat`.

Problem is in the axiomatization of special case of substring, when we have it in the form `(str.substr s 0 (1 + (str.indexof s t n)))`.
We put (if `(str.indexof s t n) != -1`, i.e. it finds something) that
`(str.substr s 0 (1 + (str.indexof s t n)))` = `(str.++ (str.substr s 0 (str.indexof s t n)) t)`.
This is not correct, it should be
`(str.substr s 0 (1 + (str.indexof s t n)))` = `(str.++ (str.substr s 0 (str.indexof s t n)) (str.at t 0))`.

Will be fixed in #331 by applying this only for the case that `t` is a string literal and we will take the character at `t[0]` directly.

### PR DESCRIPTION
**Pull request by jurajsic**
A refactoring of `handle_` functions used in `relevant_eh`.

I added a function `get_fresh_var_for_string_function` that creates a fresh string variable that replaces string functions.

Handle functions for `str.at` and `str.substr` were completely refactored, others will follow in next PRs.

Should also fix #333.

I kept the incorrect `var_eqs` stuff in `handle_substr` (issue #334). It needs to be fixed in some other PR, there are comments.

### CODE REVIEW

**Comment by jurajsic** [comment]
Benchmarks are running, it seems the changes helped some benchmarks.

**Comment by vhavlena** [comment]
Can you rebase this branch?

**Comment by jurajsic** [comment]
Results:
```
# of formulae: 133589
--------------------------------------------------
tool                                  ✅     ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  -----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-7146a45-db77a58        131438   2151  12008.59   0.09   0.00   1.55  84497    46941        760  1062       327        2
z3-noodler-97daee6-fe5ec38        131419   2170  12947.76   0.10   0.00   1.66  84479    46940        761  1088       319        2
z3-noodler-model-7146a45-db77a58  131425   2164  13580.26   0.10   0.01   1.65  84484    46941        757  1064       341        2
z3-noodler-model-97daee6-fe5ec38  131386   2203  14232.35   0.11   0.01   1.70  84447    46939        760  1097       344        2
--------------------------------------------------
```
Selected benchmarks:
```
Benchmark pyex
# of formulae: 23845
--------------------------------------------------
tool                                 ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  -----  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-7146a45-db77a58        23776    69   2899.29   0.12   0.06   1.47  20404     3372          0    67         2        0
z3-noodler-97daee6-fe5ec38        23777    68   3848.89   0.16   0.07   2.06  20405     3372          0    66         2        0
z3-noodler-model-7146a45-db77a58  23776    69   3272.61   0.14   0.08   1.47  20404     3372          0    67         2        0
z3-noodler-model-97daee6-fe5ec38  23777    68   4221.84   0.18   0.09   2.04  20405     3372          0    66         2        0
--------------------------------------------------

Benchmark full_str_int
# of formulae: 16968
--------------------------------------------------
tool                                 ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  -----  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-7146a45-db77a58        16931    37   1058.18   0.06   0.00   1.68   2506    14425         13    24         0        0
z3-noodler-97daee6-fe5ec38        16921    47   1011.72   0.06   0.00   1.38   2496    14425         13    32         2        0
z3-noodler-model-7146a45-db77a58  16931    37   1159.58   0.07   0.01   1.73   2506    14425         13    24         0        0
z3-noodler-model-97daee6-fe5ec38  16921    47   1193.99   0.07   0.01   1.64   2496    14425         13    32         2        0
--------------------------------------------------

Benchmark mosca_assertions
# of formulae: 759
--------------------------------------------------
tool                                ✅    ❌     time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ----  ----  -------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-7146a45-db77a58         426   333   174.73   0.41   0.01   3.48    116      310          0   160       173        0
z3-noodler-97daee6-fe5ec38         413   346    58.45   0.14   0.01   1.22    105      308          0   183       163        0
z3-noodler-model-7146a45-db77a58   428   331   290.57   0.68   0.01   6.55    118      310          0   160       171        0
z3-noodler-model-97daee6-fe5ec38   414   345   229.46   0.55   0.01   6.79    106      308          0   182       163        0
--------------------------------------------------

Benchmark strict_bj
# of formulae: 25206
--------------------------------------------------
tool                                 ✅    ❌     time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  -----  ----  -------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-7146a45-db77a58        24200  1006  2405.53   0.10   0.00   2.25  20318     3882        223   689        92        2
z3-noodler-97daee6-fe5ec38        24203  1003  2584.93   0.11   0.00   2.41  20320     3883        224   684        93        2
z3-noodler-model-7146a45-db77a58  24199  1007  3061.11   0.13   0.01   2.43  20317     3882        207   695       103        2
z3-noodler-model-97daee6-fe5ec38  24184  1022  2911.04   0.12   0.01   2.32  20302     3882        210   695       115        2
--------------------------------------------------
```
image
image

**Comment by jurajsic** [comment]
> Can you rebase this branch?

I will resolve the conflict (just some trace info stuff), I do not want to fully rebase, because I will lose the information about commits for experiments.

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 1]
```diff
@@ -708,13 +708,20 @@ namespace smt::noodler {
...
+        STRACE(str_axiom,
+            tout << "add_axiom literals:" << std::endl;
+            literal_vector lv;
+            for (const auto &l : ls) {
+                if (l != null_literal && l != false_literal) {
+                    lv.push_back(l);
+                }
+            }
+            ctx.display_literals_verbose(tout, lv) << "\n-----------------------------\n";
+        );
```
[the remark this answers is not in the document]
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp:724]: The call `context &ctx = get_context();` is useless.

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 2]
```diff
@@ -726,453 +733,387 @@ namespace smt::noodler {
...
+        // Note that for i > |s| (invalid case), we do not care about x, so it can still be equal to i.
+        // We can also handle some special cases in a better way.
+        expr_ref x(m);
+        if (m_util_a.is_zero(i)) {
+            // if i=0 there is nothing before v in the concatenation, so x=eps
+            x = eps;
+        } else {
+            x = mk_str_var_fresh("pre_substr");
+
+            // stronger axioms: if i = t+n for some (positive) numeral n and expression t, then, if t>=0, we can split x to two parts x = x1.x2 where |x1|=t and |x2|=n
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/theory_str_noodler.cpp:1030]: Could you add a note how the variables in the comment are mapped to c++ variables that follow?

**Review by vhavlena — APPROVED** [review]
I like the changes; good job!

File: src/smt/theory_str_noodler/theory_str_noodler.cpp (hunk 2 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp:1030]: I renamed the variables so they have the same names as in the comment.
