### PR TITLE
Fix handling of length equivalence classes

### LINKED ISSUE #334: Another incorrect result for `str.substr`
For
```
(set-logic QF_SLIA)
(set-info :status sat)

(declare-fun x () String)
(declare-fun y () String)
(declare-fun z () String)
(declare-fun s1 () String)
(declare-fun s2 () String)
(declare-fun t () String)
(declare-fun i () Int)

; force 3<=|t|<=4 using int-to-str conversion so that we force main decision procedure and we get to preprocessing
(assert (= (str.from_int i) t))
(assert (<= 100 i))
(assert (<= i 9999))

; we will use generate_equiv preprocessing rule (left sides are same) and because we incorrectly say that the substr lengths are equal, it will create incorrect equation (str.substr s1 1 (str.len t)) = (str.substr s2 1 (str.len t))
(assert (= (str.++ x y) (str.++ (str.substr s1 1 (str.len t)) z)))
(assert (= (str.++ x y) (str.substr s2 1 (str.len t))))

; force |(str.substr s1 1 (str.len t))| < |(str.len t)|
(assert (= (str.len s1) 3))
; force |(str.substr s2 1 (str.len t))| = |(str.len t)|
(assert (= (str.len s2) 5))

(check-sat)
```
we return `unsat` even though it is `sat`.

The problem is that in axiomization of `(str.substr s i l)`, we add `(str.len (str.substr s i l))` and `l` to the same equivalence class (using out `var_eqs`). This is not correct, `(str.substr s i l)` can be shorter than `l`, in the cases when `l` is larger than the rest of the substring of `s` starting at position `i`.

In the formula, this means that we put both `(str.++ (str.substr s1 1 (str.len t))` and `(str.substr s2 1 (str.len t))` in the same (length) equivalence class, which is not correct, the first substring will have length 2 while the second one will have either length 3 or 4 (based on the length of `t`). The preprocessing rule `generate_equiv` will then generate the equality between the two substrings, which is not correct.

I am trying to fix it in #331

### PR DESCRIPTION
**Pull request by vhavlena**
This pull request fixes the handling of variable equivalences in the Noodler string solver, especially regarding the precision of equivalence relations. The main focus is to avoid incorrect equivalence assumptions by distinguishing between "precise" and "imprecise" relations and by verifying imprecise relations using the solver context and LIA (Linear Integer Arithmetic) checks.

### CODE REVIEW

**Comment by vhavlena** [comment]
The results are a bit worse:

```
# of formulae: 106648
--------------------------------------------------
tool                            ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------  ------  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-5c688c8-1c39000  105835   813  10005.81   0.09   0.00   1.34  64054    41781        537   209        67        0
z3-noodler-ab0c64e-1c39000  105836   812   9281.87   0.09   0.00   1.19  64054    41782        537   209        66        0
cvc5-1.3.2                  100288  6360  73410.38   0.73   0.01   6.28  61122    39166        132  6220         0        8
z3-4.15.4                    96858  9790  95319.17   0.98   0.00   6.71  57869    38989       2227  5815      1748        0
--------------------------------------------------

Benchmark pyex
# of formulae: 23845
--------------------------------------------------
tool                           ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------  -----  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-5c688c8-1c39000  23775    70   2721.96   0.11   0.07   0.96  20404     3371          0    69         1        0
z3-noodler-ab0c64e-1c39000  23775    70   2409.64   0.10   0.06   1.04  20403     3372          0    69         1        0
cvc5-1.3.2                  23835    10   6935.50   0.29   0.07   3.51  20414     3421          0    10         0        0
z3-4.15.4                   22745  1100  45790.70   2.01   0.13   9.52  19474     3271          0   926       174        0
--------------------------------------------------

Benchmark full_str_int
# of formulae: 16968
--------------------------------------------------
tool                           ✅    ❌      time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------  -----  ----  --------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-5c688c8-1c39000  16929    39   1465.09   0.09   0.00   2.03   2504    14425         13    26         0        0
z3-noodler-ab0c64e-1c39000  16930    38    968.36   0.06   0.00   1.24   2505    14425         13    25         0        0
cvc5-1.3.2                  16963     5   4534.25   0.27   0.01   1.25   2521    14442          0     5         0        0
z3-4.15.4                   16727   241  18619.05   1.11   0.00   6.67   2473    14254          0   238         3        0
--------------------------------------------------
```

image

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 1]
```diff
@@ -1083,7 +1083,7 @@ namespace smt::noodler {
         // 0 <= i <= |s| && |s|-i < l  -> |v| = |s|-i
         add_axiom({~i_ge_0, ~i_le_ls, ls_ge_l_plus_i, mk_eq(lv, mk_sub(ls, i), false)});
         // remember l=|v|
-        this->var_eqs.add(expr_ref(l, m), v); // TODO: NOT CORRECT, in case where l > |s|-i, the length of v is |s|-i, needs to be fixed somehow (see issue #334)
+        this->var_eqs.add(expr_ref(l, m), v, false); // equivalence might not be precise (we need to check whether the equivalence holds in final_check)
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler.cpp:1087]: Can you keep the info when the equivalence is not precise in the comment?

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 2]
```diff
@@ -1057,7 +1057,7 @@ namespace smt::noodler {
                     // t>=0 -> |x2| = n (not completely needed, helps z3)
                     add_axiom({~i_ge_0, ~i_le_ls, ~t_ge_0, mk_eq(m_util_s.str.mk_length(x2), n, false)});
                     // |x1| = t (we do not need to put it in an axiom, we will have that |x| = i later from which |x1| = t follows)
-                    this->var_eqs.add(expr_ref(t, m), x1); // TODO: PROBABLY NOT CORRECT, in case where t<0, needs checking, I am unable to create a formula where this shows up
+                    this->var_eqs.add(expr_ref(t, m), x1, false); // equivalence might not be precise (we need to check whether the equivalence holds in final_check)
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler.cpp]: Similarly here, keep the info when it might not be precise in the comment.

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp [hunk 3]
```diff
@@ -737,8 +737,9 @@ namespace smt::noodler {
     lbool theory_str_noodler::solve_underapprox(const Formula& instance, const AutAssignment& aut_assignment,
                                                 const std::unordered_set<BasicTerm>& init_length_sensitive_vars,
                                                 std::vector<TermConversion> conversions) {
+        context& ctx = get_context();
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:740]: Why this code? Why not just use `ctx` directly (instead of local var)?

File: src/smt/theory_str_noodler/var_union_find.h [hunk 4]
```diff
@@ -90,22 +111,76 @@ namespace smt::noodler {
          * 
          * @return Equivalence classes consisting of BasicTerms
          */
-        BasicTermEqiv get_equivalence_bt(const AutAssignment& aut_ass) const {
+        BasicTermEqiv get_equivalence_bt(const AutAssignment& aut_ass, smt::context& ctx, seq_util& m_util_s) const {
             std::vector<std::set<BasicTerm>> ret;
-            for(const auto& t : this->un_find) {
-                std::set<BasicTerm> st;
+            // enodes are sometimes not precise (they do not relate terms to 
+            // the same equivalence class even though they are indeed equivalent).
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/var_union_find.h]: I do not understand why this comment is here.

File: src/smt/theory_str_noodler/var_union_find.h [hunk 5]
```diff
@@ -90,22 +111,76 @@ namespace smt::noodler {
...
-                    if(len != -1 && len > 1) {
+                    expr* var = s.m_key;
+                    bool precise = s.m_value;
+                    // we consider only variables (not concatenation or other complex terms)
+                    // therefore, s = variable
+                    if(!is_app(var) || to_app(var)->get_num_args() != 0) {
+                        continue;
+                    }
+                    BasicTerm bvar = util::get_variable_basic_term(var);
+                    if (len != -1 && len > 1) {
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/var_union_find.h]:
```suggestion
                    if (len > 1) {
```

File: src/test/noodler/e2e/substr-len.smt2 [hunk 6]
```diff
@@ -0,0 +1,26 @@
...
+; we will use generate_equiv preprocessing rule (left sides are same) and because we incorrectly say that the substr lengths are equal, it will create incorrect equation (str.substr s1 1 (str.len t)) = (str.substr s2 1 (str.len t))
+(assert (= (str.++ x y) (str.++ (str.substr s1 1 (str.len t)) z)))
+(assert (= (str.++ x y) (str.substr s2 1 (str.len t))))
+
+; force |(str.substr s1 1 (str.len t))| < |(str.len t)|
+(assert (= (str.len s1) 3))
+; force |(str.substr s2 1 (str.len t))| = |(str.len t)|
+(assert (= (str.len s2) 5))
+
+(check-sat)
```
Comment (jurajsic) [inline src/test/noodler/e2e/substr-len.smt2]: Missing final newline:
```suggestion
(check-sat)

```

File: src/test/noodler/e2e/pyex-eq-class.smt2 [hunk 7]
```diff
@@ -0,0 +1,13 @@
+(set-logic QF_S) ;(set-logic ALL_SUPPORTED)
```
Comment (jurajsic) [inline src/test/noodler/e2e/pyex-eq-class.smt2:1]: Where is this .smt2 from?

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp (hunk 3 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:740]: Yes, you can. I am kind of used to this pattern. It is a reference, so there is basically no performance issue.

File: src/smt/theory_str_noodler/var_union_find.h (hunk 4 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/var_union_find.h]: I meant something like: if two terms are equal, it doesn't mean that they are in the same equivalence class. If they are in the same equivalence class, they are equal.

File: src/test/noodler/e2e/pyex-eq-class.smt2 (hunk 7 above)
Comment (vhavlena) [reply src/test/noodler/e2e/pyex-eq-class.smt2:1]: pyex (don't know exactly which one. It comes from my collection of interesting benchmarks that were used for debugging at some point).

File: src/smt/theory_str_noodler/theory_str_noodler.cpp (hunk 2 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp]: I added a comment.

File: src/smt/theory_str_noodler/theory_str_noodler.cpp (hunk 1 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp:1087]: I added a comment.

File: src/smt/theory_str_noodler/var_union_find.h (hunk 4 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/var_union_find.h]: I understand that, I do not understand the position of this comment. Should it be a bit lower, when there is something happening with enodes?

File: src/test/noodler/e2e/pyex-eq-class.smt2 (hunk 7 above)
Comment (jurajsic) [reply src/test/noodler/e2e/pyex-eq-class.smt2:1]: Ah ok, that's cool.

File: src/smt/theory_str_noodler/var_union_find.h (hunk 4 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/var_union_find.h]: Ah, ok, I moved it a bit lower.

**Review by jurajsic — APPROVED** [review]
