### PR TITLE
Theory combination

### LINKED ISSUE #199: Incorrect result for uninterpreted bool function taking string
For
```
(declare-fun x () String)
(declare-fun y () String)
(declare-fun sb (String) Bool)

(assert (= (sb x) (not (sb y))))
(check-sat)
```
we return `sat` instead of `unsat` with model
```
(
  (define-fun y () String
    "a")
  (define-fun x () String
    "a")
  (define-fun sb ((x!0 String)) Bool
    true)
)
```

_Originally posted by @jurajsic in https://github.com/VeriFIT/z3-noodler/issues/194#issuecomment-2470572578_

### PR DESCRIPTION
**Pull request by vhavlena**
This PR adds a quite naive support of theory combination with the noodler string theory.

### CODE REVIEW

**Comment by vhavlena** [comment]
```
# of formulae: 106648
--------------------------------------------------
tool                            ✅    ❌        time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------  ------  ----  ----------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-901d1f9-f4ae1a1  105709   939    10900.34   0.10   0.00   1.45  64031    41678        642   237        60        0
z3-noodler-52106d2-f09b1eb  105710   938    11010.94   0.10   0.00   1.47  64032    41678        642   236        60        0
cvc5-1.3.1                  100246  6402    70919.81   0.71   0.00   6.22  61078    39168        132  6262         0        8
z3-4.15.3                    96897  9751    94175.26   0.97   0.00   6.67  57904    38993       2228  5713      1810        0
ostrich-2-fmcad25           103115  3533  1034421.06  10.03   2.01  20.76  62273    40842          3  3529         0        1
--------------------------------------------------
```

image

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp [hunk 1]
```diff
@@ -1144,4 +1151,76 @@ namespace smt::noodler {
...
+            sbuffer<theory_var>::iterator it2 = it1;
+            ++it2;
+            for (; it2 != end1; ++it2) {
+                theory_var v2 = *it2;
+                enode * n2 = get_enode(v2);
+                sort * s2 = n2->get_expr()->get_sort();
+                app * eq = ctx.mk_eq_atom(n1->get_expr(), n2->get_expr());
+
+                // disequation of inter-theory variables are always relevant
+                if(ctx.is_diseq(n1, n2)) {
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1207]: What is happening here?

**Review by jurajsic — APPROVED** [review]

**Comment by jurajsic** [comment]
Did you try something else other than the two benchmarks in the issue? Maybe something with lengths.

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp (hunk 1 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1207]: There might (and I have seen such cases) be a problem with relevancy propagation of these newly created disequations between shared variables. We haven't seen them before, therefore they are not relevant and hence we could skip them in the final check.

**Comment by vhavlena** [comment]
> Did you try something else other than the two benchmarks in the issue? Maybe something with lengths.

Just these two (and a couple of more simple variants where I was testing some features). I hope we could do more rigorous testing with Marek (student od Lukas). But there is a bit problem with benchmarks (SMT-Lib seems to lack these kind of benchmarks). 

The lengths should not be a problem (current benchmarks seem  not to have shared variables that need to be handled using this approach.

File: src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp (hunk 1 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/theory_str_noodler_final_check.cpp:1207]: Oh ok, I get it now.
