### PR TITLE
Fix models in `DiseqLengthHeuristicProcedure`

### LINKED ISSUE #339: incorrect model with uninterpreted function
```
(declare-datatypes ((Value 0)) (((s_int (unwrap_int Int)) (s_bool (unwrap_bool Bool)) (s_str (unwrap_str String)) (s_dict (unwrap_dict (Array String Value))))))
(declare-fun iv0 () String)
(declare-fun aaa (String) (Array String Value))
(declare-fun source () String)
(declare-fun iv1 () Bool)
(assert (= iv0 (unwrap_str (select (aaa source) "id"))))
(assert (= iv1 (str.in.re iv0 (re.++ (re.++ (re.* re.allchar) (str.to_re "abcdefg")) (re.* re.allchar)))))
(assert iv1)
(assert (is-s_str (select (aaa source) "id")))
(check-sat)
sat
(get-model)
(
  (define-fun source () String
    "aaa")
  (define-fun iv1 () Bool
    true)
  (define-fun iv0 () String
    "aaaaaaa")
  (define-fun aaa ((x!0 String)) (Array String Value)
    ((as const (Array String Value)) (s_str "aaaaaaa")))
)
```
tested version: v1.5.0

tests on standard z3, the model is correct:
```
(declare-datatypes ((Value 0)) (((s_int (unwrap_int Int)) (s_bool (unwrap_bool Bool)) (s_str (unwrap_str String)) (s_dict (unwrap_dict (Array String Value))))))
(declare-fun iv0 () String)
(declare-fun aaa (String) (Array String Value))
(declare-fun source () String)
(declare-fun iv1 () Bool)
(assert (= iv0 (unwrap_str (select (aaa source) "id"))))
(assert (= iv1 (str.in.re iv0 (re.++ (re.++ (re.* re.allchar) (str.to_re "abcdefg")) (re.* re.allchar)))))
(assert iv1)
(assert (is-s_str (select (aaa source) "id")))
(check-sat)
sat
(get-model)
(
  (define-fun source () String
    "id")
  (define-fun iv1 () Bool
    true)
  (define-fun iv0 () String
    "abcdefg")
  (define-fun aaa ((x!0 String)) (Array String Value)
    ((as const (Array String Value)) (s_str "abcdefg")))
)

### PR DESCRIPTION
**Pull request by jurajsic**
Fixes #339 

There was a problem in `DiseqLengthHeuristicProcedure` where we did not use the correct variable in substitution map while finding model.

I also added function `substitute_var()` in preprocessing, I was planning to remove substituted vars from automata assignment, but it is currently not possible, as we use empty automata to check if preprocessing got to invalid state. We should probably rewrite the way preprocessing is called, we should check after every rule if we did not get to unsat.

### CODE REVIEW

**Comment by jurajsic** [comment]
Results:
```
# of formulae: 133722
--------------------------------------------------
tool                                  ✅     ❌       time    avg    med    std    sat    unsat    unknown    TO    MO+ERR    other
--------------------------------  ------  -----  ---------  -----  -----  -----  -----  -------  ---------  ----  --------  -------
z3-noodler-d15c6be-db77a58        131599   2123   13195.36   0.10   0.00   1.65  84654    46945        757  1260       102        4
z3-noodler-76f75eb-db77a58        131588   2134   13166.29   0.10   0.00   1.65  84643    46945        767  1260       103        4
z3-noodler-model-d15c6be-db77a58  131587   2135   14294.63   0.11   0.01   1.67  84643    46944        755  1268       108        4
z3-noodler-model-76f75eb-db77a58  131576   2146   14364.81   0.11   0.01   1.69  84632    46944        766  1268       108        4
--------------------------------------------------
```
image
image

There is small improvement in `strict_bj` for some reason, and some degradation in `matching`, but that is probably the random degradation we sometimes get.

File: src/smt/theory_str_noodler/formula_preprocess.cpp [hunk 1]
```diff
@@ -346,20 +346,19 @@ namespace smt::noodler {
...
                 // and we can add Y -> X to subst map (+ propagate that X is also conversion var)
                 this->conversion_vars.insert(left_var);
-                this->substitution_map[pr.second.get_right_side()[0]] = {left_var};
+                substitute_var(pr.second.get_right_side()[0], {left_var});
             } else {
                 // otherwise we do not need to put anything in substitution map and we just need to remember the inclusion for model generation
                 removed_inclusions_for_model.push_back(pr.second);
             }
 
-            this->formula.remove_predicate(pr.first);
```
Comment (vhavlena) [inline src/smt/theory_str_noodler/formula_preprocess.cpp:359]: Why this change? We need to keep the predicates, now?

**Review by vhavlena — APPROVED** [review]
Nice!

File: src/smt/theory_str_noodler/formula_preprocess.cpp (hunk 1 above)
Comment (jurajsic) [reply src/smt/theory_str_noodler/formula_preprocess.cpp:359]: I just moved it before previous `if` (so that the substituted var does not occur in the formula).
