### PR TITLE
Fix: `is_digit` assertion violation

### LINKED ISSUE #315: Assertion violation in rewriter_def.h:226
I encountered an ASSERTION VIOLATION in rewriter_def.h.
```smt2
(set-logic QF_SLIA)
(declare-fun s () String)
(assert (= 1 (str.indexof (str.++ "si") (ite (str.is_digit (str.++ s "si")) "i" ""))))
(check-sat)
```
Output:
```
ASSERTION VIOLATION
File: z3-noodler/src/ast/rewriter/rewriter_def.h
Line: 226
UNEXPECTED CODE WAS REACHED.
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
C
ASSERTION VIOLATION
File: z3-noodler/src/util/vector.h
Line: 947
!empty()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
C
ASSERTION VIOLATION
File: z3-noodler/src/util/vector.h
Line: 917
idx < size()
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
C
Segmentation fault (core dumped)
```
Version:
```
Z3 version 4.15.1 - 64 bit 
- build hashcode 500da66e6fcd1b72d43812c066ce23b4fce98e32 
- mata hashcode fe5ec3898a2bfbaebafcfa163b27bd4951cece0c
```

### PR DESCRIPTION
**Pull request by vhavlena**
This pull request introduces a fix in the `theory_str_noodler.cpp` (to use `expr_ref` instead of a raw pointer) and adds a new end-to-end test for string digit handling in the Noodler SMT solver.

### CODE REVIEW

File: src/test/noodler/e2e/rewriter-assert.smt2 [hunk 1]
```diff
@@ -0,0 +1,5 @@
+(set-logic QF_SLIA)
+(set-info :status unsat)
+(declare-fun s () String)
+(assert (= 1 (str.indexof (str.++ "si") (ite (str.is_digit (str.++ s "si")) "i" ""))))
+(check-sat)
```
Comment (jurajsic) [inline src/test/noodler/e2e/rewriter-assert.smt2]:
```suggestion
(check-sat)

```

**Review by jurajsic — APPROVED** [review]
