### PR TITLE
Fix: Assert in quantified formulae

### LINKED ISSUE #309: Assertion violation in theory_str_noodler.cpp:2452 on input with `forall/str.len`
I encountered an ASSERTION VIOLATION in theory_str_noodler.cpp when using quantifiers (forall) with string constraints.
Example:
```smt2
(set-logic ALL)
(assert (forall ((s String)) 
    (>= (str.len s) 0)
))
(check-sat)
```
Output:
```
ASSERTION VIOLATION
File: z3-noodler/src/smt/theory_str_noodler/theory_str_noodler.cpp
Line: 2452
is_app(e)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
C
ASSERTION VIOLATION
File: z3-noodler/src/ast/ast.h
Line: 963
is_app(n)
(C)ontinue, (A)bort, (S)top, (T)hrow exception, Invoke (G)DB
C
sat
```
Version:
```
Z3 version 4.15.1 - 64 bit 
- build hashcode 97daee6a0105c052b6674ace3418e3460f751591 
- mata hashcode fe5ec3898a2bfbaebafcfa163b27bd4951cece0c
```

### PR DESCRIPTION
**Pull request by vhavlena**
This pull request introduces a minor fix for handling quantified variables in `mark_expression_as_length`.

### CODE REVIEW

File: src/smt/theory_str_noodler/theory_str_noodler.cpp [hunk 1]
```diff
@@ -2448,6 +2448,9 @@ namespace smt::noodler {
             len_vars.insert(e);
             return;
         }
+        if(is_var(e)) {
```
Comment (jurajsic) [inline src/smt/theory_str_noodler/theory_str_noodler.cpp:2453]: There should be some comment here why this check.

File: src/test/noodler/e2e/forall-simple.smt2 [hunk 2]
```diff
@@ -0,0 +1,6 @@
+(set-logic ALL)
+(set-info :status sat)
+(assert (forall ((s String)) 
+    (>= (str.len s) 0)
+))
+(check-sat)
```
Comment (jurajsic) [inline src/test/noodler/e2e/forall-simple.smt2]:
```suggestion
(check-sat)

```

File: src/smt/theory_str_noodler/theory_str_noodler.cpp (hunk 1 above)
Comment (vhavlena) [reply src/smt/theory_str_noodler/theory_str_noodler.cpp:2453]: Done.

**Review by jurajsic — APPROVED** [review]
